### ISSUE TITLE
bruh the file for autobleem is corrupted

### ISSUE THREAD

**Issue by FireWorkDamp** [KMFDManic/AutoBleem-Xtreme#1]
litterally i can't open the file in anyway
i just wanna play some brutal doom on my psc

**Comment by KMFDManic** [comment]
You just need to double click the self extracting installer exe to install autobleem to your drive.  If it's not working, you likely have virus protection or such blocking the file as a false positive.

**Comment by KMFDManic** [comment]
Due to lack of response or PEBCAC, closing this issue.
